### ISSUE TITLE
Dashboard refresh when there is a playlist

### ISSUE THREAD

**Issue by Rudd-O** [jtbgroup/kodi-playlist-card#5]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Whenever I start a smart playlist in Kodi, any dashboard that has the playlist card will cause a whole-page refresh.  I can see the whole page being drawn, including the playlist items on the playlist, then bam, refresh.  Infinite loop too.

This does not happen when the card is empty because Kodi is off, or there is no playlist active.

I can't get any logs from the Web Developer inspector / console because I can't stop the browser from refreshing.  Profoundly sorry I don't know how to give you more details.

### What version of a card has described problem?

4.4.2

### What was the last working version card?

I don't know but this wasn't happening a week ago

### What browser (browsers/apps) does have this problem?

Happens in Safari, Android WebView and Firefox

### What version of Home Assistant do you use?

2023.01

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:kodi-playlist-card
              entity: sensor.kodi_media_sensor_playlist
              show_thumbnail: true
              show_thumbnail_border: false
              show_thumbnail_overlay: true
              show_line_separator: false
              hide_last_line_separator: false
              outline_color: var(--primary-text-color)
              items_container_scrollable: true
              items_container_height: 300px
```
```


### Javascript errors shown in the browser's console (if applicable)

```shell
Help me!  How can I stop refresh so I can get you an error message?
```
